name: HelenCore CI/CD Pipeline

on:
  push:
    branches:
      - main
      - preview/**
  pull_request:
    branches:
      - main

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Production
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Vercel (Production)
        run: |
          npm install -g vercel
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-preview:
    if: startsWith(github.ref, 'refs/heads/preview/')
    runs-on: ubuntu-latest
    name: 🧪 Deploy Preview Environment
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Vercel (Preview)
        run: |
          npm install -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }} --confirm --yes

  comment-preview-url:
    needs: deploy-preview
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: 💬 Comment Preview URL
    steps:
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          header: preview-url
          message: |
            ✅ Preview deployed! Check it here: [Vercel Preview](https://vercel.com/YOUR_TEAM_NAME/YOUR_PROJECT_NAME/preview)
